version: "3.9"
services:
  web:
    build: ./frontend
    ports:
      - "80:80"
    networks: [fuqnet]

  api:
    build: ./backend
    ports:
      - "4000:4000"
    networks: [fuqnet]

networks:
  fuqnet:
