// This workflow builds, pushes, and deploys the app
name: CI
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE: ${{ github.repository }}-web
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & build frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Build & push Docker image
        run: |
          docker build -t $REGISTRY/$IMAGE:${{ github.sha }} .
          echo ${{ secrets.GHCR_TOKEN }} | docker login $REGISTRY -u ${{ github.actor }} --password-stdin
          docker push $REGISTRY/$IMAGE:${{ github.sha }}

      - name: Deploy on DellR720
        uses: appleboy/ssh-action@v0.2.0
        with:
          host: ${{ secrets.R720_HOST }}
          username: ${{ secrets.R720_USER }}
          key: ${{ secrets.R720_SSH_KEY }}
          script: |
            cd /srv/iongiveafuq
            docker compose pull
            docker compose up -d --remove-orphans
